import Foundation
import Observation
#if canImport(UIKit)
import UIKit
#endif

@Observable
final class GameEngine {

    var state = GameState.new()
    /// Bumped every frame so time-decaying visuals (completion glow) redraw.
    var now = Date.timeIntervalSinceReferenceDate
    /// Timestamp of the most recent completion per loop, for the pulse flash.
    var lastCompletion = [Double](repeating: -999, count: LoopConfig.count)
    var offlineReport: OfflineReport?
    /// Recomputed a few times a second and read by every readout, so the views
    /// never run the cascade math themselves.
    var cachedRates = Rates()

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastRateRefresh: Double = 0
    @ObservationIgnored private var lastTick = Date.timeIntervalSinceReferenceDate
    @ObservationIgnored private var lastSave = Date.timeIntervalSinceReferenceDate
    @ObservationIgnored private var recordCompletions = true

    init() {
        load()
        applyOfflineProgress()
        cachedRates = rates()
        start()
    }

    // MARK: - Clock

    func start() {
        timer?.invalidate()
        lastTick = Date.timeIntervalSinceReferenceDate
        let t = Timer(timeInterval: 1.0 / 30.0, repeats: true) { [weak self] _ in self?.frame() }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        state.lastSeen = Date()
        save()
    }

    private func frame() {
        let t = Date.timeIntervalSinceReferenceDate
        let dt = min(max(t - lastTick, 0), 1.0)
        lastTick = t
        now = t
        tick(dt)
        state.playTime += dt
        if t - lastRateRefresh > 0.25 {
            lastRateRefresh = t
            cachedRates = rates()
        }
        if t - lastSave > 5 {
            lastSave = t
            state.lastSeen = Date()
            save()
        }
    }

    // MARK: - Simulation

    func tick(_ dt: Double) {
        guard dt > 0 else { return }
        deliver(sparkGain * dt, to: 0, depth: 0)
        runAutobuyers()
    }

    /// Charge per second generated by the Spark itself.
    var sparkGain: Double {
        var s = 1.0
        if state.nodes.contains("speed1") { s *= 1.5 }
        if state.nodes.contains("speed2") { s *= 2.0 }
        if state.nodes.contains("speed3") { s *= 3.0 }
        return s * (1 + state.flywheel)
    }

    /// Push charge into a loop; a completion recurses into the loops it feeds.
    private func deliver(_ amount: Double, to index: Int, depth: Int) {
        guard index < LoopConfig.count, depth < 32 else { return }
        guard state.loops[index].unlocked, amount > 0 else { return }

        state.loops[index].charge += amount * intakeMultiplier(index)
        let need = requirement(index)
        guard state.loops[index].charge >= need else { return }

        var count: Double
        if has(.overflowValve, index) {
            // Excess rolls forward, so one delivery can complete many cycles.
            count = (state.loops[index].charge / need).rounded(.down)
            state.loops[index].charge -= count * need
        } else {
            count = 1
            state.loops[index].charge = 0
        }
        guard count > 0 else { return }
        complete(index, count: count, depth: depth)
    }

    private func complete(_ index: Int, count: Double, depth: Int) {
        let cfg = LoopConfig.all[index]
        state.loops[index].completions += count

        let energy = cfg.baseYield * yieldMultiplier(index) * count
        state.energy += energy
        state.energyThisRun += energy
        state.lifetimeEnergy += energy

        if cfg.baseResonance > 0 || has(.resonator, index) {
            let res = cfg.baseResonance * resonanceMultiplier(index) * count
            state.resonance += res
        }

        if has(.flywheel, index) {
            state.flywheel += Balance.flywheelPerCompletion * count
        }

        if recordCompletions { lastCompletion[index] = now }

        let pulse = pulseStrength(index) * count
        deliver(pulse, to: index + 1, depth: depth + 1)
        if has(.splitter, index) {
            deliver(pulse * 0.5, to: index + 2, depth: depth + 1)
        }
    }

    // MARK: - Derived multipliers

    func requirement(_ index: Int) -> Double {
        var r = LoopConfig.all[index].requirement
        if has(.governor, index) { r *= 0.75 }
        return max(0.05, r)
    }

    func intakeMultiplier(_ index: Int) -> Double {
        var m = pow(Balance.intakeStep, Double(state.loops[index].intakeLevel))
        if has(.intakeCoil, index) { m *= 1.75 }
        return m
    }

    func pulseStrength(_ index: Int) -> Double {
        var p = Balance.basePulse * pow(Balance.pulseStep, Double(state.loops[index].pulseLevel))
        if has(.amplifier, index) { p *= 2 }
        if state.nodes.contains("pulseGlobal") { p *= 1.5 }
        return p
    }

    func yieldMultiplier(_ index: Int) -> Double {
        var m = pow(Balance.yieldStep, Double(state.loops[index].yieldLevel))
        if has(.condenser, index) { m *= 3 }
        if state.nodes.contains("yieldGlobal") { m *= 3 }
        m *= echoMultiplier
        return m
    }

    func resonanceMultiplier(_ index: Int) -> Double {
        has(.resonator, index) ? 4 : 1
    }

    /// Every Echo ever earned permanently sweetens Energy.
    var echoMultiplier: Double { 1 + 0.02 * state.lifetimeEchoes }

    func has(_ module: ModuleID, _ index: Int) -> Bool {
        state.loops[index].modules.contains(module)
    }

    // MARK: - Upgrades

    func yieldCost(_ i: Int) -> Double {
        LoopConfig.all[i].upgradeBase * pow(Balance.yieldCostGrowth, Double(state.loops[i].yieldLevel))
    }
    func intakeCost(_ i: Int) -> Double {
        LoopConfig.all[i].upgradeBase * 3 * pow(Balance.intakeCostGrowth, Double(state.loops[i].intakeLevel))
    }
    func pulseCost(_ i: Int) -> Double {
        LoopConfig.all[i].upgradeBase * 8 * pow(Balance.pulseCostGrowth, Double(state.loops[i].pulseLevel))
    }

    @discardableResult func buyYield(_ i: Int) -> Bool {
        let c = yieldCost(i)
        guard state.energy >= c else { return false }
        state.energy -= c
        state.loops[i].yieldLevel += 1
        return true
    }
    @discardableResult func buyIntake(_ i: Int) -> Bool {
        let c = intakeCost(i)
        guard state.energy >= c else { return false }
        state.energy -= c
        state.loops[i].intakeLevel += 1
        return true
    }
    @discardableResult func buyPulse(_ i: Int) -> Bool {
        let c = pulseCost(i)
        guard state.energy >= c else { return false }
        state.energy -= c
        state.loops[i].pulseLevel += 1
        return true
    }

    /// The next loop that can be brought online, if any.
    var nextLockedTier: Int? {
        for i in 0..<LoopConfig.count where !state.loops[i].unlocked { return i }
        return nil
    }

    @discardableResult func unlockLoop(_ i: Int) -> Bool {
        guard i < LoopConfig.count, !state.loops[i].unlocked else { return false }
        guard i == 0 || state.loops[i - 1].unlocked else { return false }
        let c = LoopConfig.all[i].unlockCost
        guard state.energy >= c else { return false }
        state.energy -= c
        state.loops[i].unlocked = true
        haptic(.heavy)
        return true
    }

    // MARK: - Modules

    func slots(for index: Int) -> Int {
        var n = Balance.baseModuleSlots
        if state.nodes.contains("slots1") { n += 1 }
        if state.nodes.contains("slots2") { n += 1 }
        return n
    }

    func moduleCost(_ m: ModuleID) -> Double {
        let owned = Double(state.modulesOwned[m.rawValue] ?? 0)
        return m.baseCost * pow(Balance.moduleCostGrowth, owned)
    }

    func canInstall(_ m: ModuleID, on index: Int) -> Bool {
        guard state.loops[index].unlocked else { return false }
        guard !state.loops[index].modules.contains(m) else { return false }
        guard state.loops[index].modules.count < slots(for: index) else { return false }
        return state.resonance >= moduleCost(m)
    }

    @discardableResult func install(_ m: ModuleID, on index: Int) -> Bool {
        guard canInstall(m, on: index) else { return false }
        state.resonance -= moduleCost(m)
        state.modulesOwned[m.rawValue, default: 0] += 1
        state.loops[index].modules.append(m)
        haptic(.medium)
        return true
    }

    /// Pulling a module frees the slot but not the Resonance — moving costs you.
    func uninstall(_ m: ModuleID, from index: Int) {
        guard let pos = state.loops[index].modules.firstIndex(of: m) else { return }
        state.loops[index].modules.remove(at: pos)
        state.modulesOwned[m.rawValue] = max(0, (state.modulesOwned[m.rawValue] ?? 1) - 1)
    }

    // MARK: - The Array

    func nodeOwned(_ id: String) -> Bool { state.nodes.contains(id) }

    func nodeUnlocked(_ node: ArrayNode) -> Bool {
        node.requires.allSatisfy { state.nodes.contains($0) }
    }

    func canBuyNode(_ node: ArrayNode) -> Bool {
        !nodeOwned(node.id) && nodeUnlocked(node) && state.echoes >= node.cost
    }

    @discardableResult func buyNode(_ node: ArrayNode) -> Bool {
        guard canBuyNode(node) else { return false }
        state.echoes -= node.cost
        state.nodes.insert(node.id)
        haptic(.medium)
        return true
    }

    // MARK: - Collapse (prestige)

    var canCollapse: Bool {
        state.deepestTier >= Balance.collapseUnlockTier && pendingEchoes >= 1
    }

    var pendingEchoes: Double {
        guard state.energyThisRun > 1e6 else { return 0 }
        var e = 2.5 * pow(log10(state.energyThisRun) - 6, 1.55)
        e *= 1 + 0.35 * Double(max(0, state.deepestTier - Balance.collapseUnlockTier))
        if state.nodes.contains("echoGain") { e *= 1.6 }
        return max(0, e.rounded(.down))
    }

    /// Energy needed for the next whole Echo — the classic "just one more" readout.
    var energyForNextEcho: Double {
        let target = pendingEchoes + 1
        var scale = 1.0
        scale *= 1 + 0.35 * Double(max(0, state.deepestTier - Balance.collapseUnlockTier))
        if state.nodes.contains("echoGain") { scale *= 1.6 }
        let raw = target / (2.5 * scale)
        return pow(10, pow(raw, 1 / 1.55) + 6)
    }

    func collapse() {
        guard canCollapse else { return }
        let gained = pendingEchoes
        let keep = state.nodes.contains("keepRes")
        let keptResonance = keep ? state.resonance : 0
        let keptModules: [[ModuleID]] = keep ? state.loops.map(\.modules) : []
        let keptOwned = keep ? state.modulesOwned : [:]

        var fresh = GameState.new()
        fresh.echoes = state.echoes + gained
        fresh.lifetimeEchoes = state.lifetimeEchoes + gained
        fresh.lifetimeEnergy = state.lifetimeEnergy
        fresh.nodes = state.nodes
        fresh.collapses = state.collapses + 1
        fresh.playTime = state.playTime
        fresh.resonance = keptResonance
        fresh.modulesOwned = keptOwned

        if state.nodes.contains("seed1") {
            fresh.loops[1].unlocked = true
            fresh.loops[2].unlocked = true
        }
        if state.nodes.contains("seed2") {
            for i in 1...4 { fresh.loops[i].unlocked = true }
        }
        if state.nodes.contains("startEnergy") { fresh.energy = 1e6 }

        if keep {
            for i in 0..<min(keptModules.count, fresh.loops.count) where fresh.loops[i].unlocked {
                fresh.loops[i].modules = keptModules[i]
            }
        }

        state = fresh
        lastCompletion = [Double](repeating: -999, count: LoopConfig.count)
        haptic(.heavy)
        save()
    }

    // MARK: - Autobuyers

    private func runAutobuyers() {
        let unlockedTiers = (0..<LoopConfig.count).filter { state.loops[$0].unlocked }
        if state.nodes.contains("autoYield") {
            for i in unlockedTiers where yieldCost(i) <= state.energy * 0.5 { buyYield(i) }
        }
        if state.nodes.contains("autoIntake") {
            for i in unlockedTiers where intakeCost(i) <= state.energy * 0.5 { buyIntake(i) }
        }
        if state.nodes.contains("autoPulse") {
            for i in unlockedTiers where pulseCost(i) <= state.energy * 0.5 { buyPulse(i) }
        }
        if state.nodes.contains("autoLoop"), let next = nextLockedTier {
            unlockLoop(next)
        }
    }

    // MARK: - Rate estimates (for the readouts)

    struct Rates {
        var completionsPerSecond = [Double](repeating: 0, count: LoopConfig.count)
        var energyPerSecond: Double = 0
        var resonancePerSecond: Double = 0
    }

    func rates() -> Rates {
        var r = Rates()
        var chargeIn = [Double](repeating: 0, count: LoopConfig.count)
        chargeIn[0] = sparkGain * intakeMultiplier(0)

        for i in 0..<LoopConfig.count {
            guard state.loops[i].unlocked else { continue }
            let theoretical = chargeIn[i] / requirement(i)
            // Without an Overflow Valve a loop can never outpace its feeder.
            if i == 0 || has(.overflowValve, i) {
                r.completionsPerSecond[i] = theoretical
            } else {
                r.completionsPerSecond[i] = min(theoretical, r.completionsPerSecond[i - 1])
            }
            let emitted = r.completionsPerSecond[i] * pulseStrength(i)
            if i + 1 < LoopConfig.count {
                chargeIn[i + 1] += emitted * intakeMultiplier(i + 1)
            }
            if has(.splitter, i), i + 2 < LoopConfig.count {
                chargeIn[i + 2] += emitted * 0.5 * intakeMultiplier(i + 2)
            }
        }

        for i in 0..<LoopConfig.count where state.loops[i].unlocked {
            let cfg = LoopConfig.all[i]
            r.energyPerSecond += r.completionsPerSecond[i] * cfg.baseYield * yieldMultiplier(i)
            if cfg.baseResonance > 0 || has(.resonator, i) {
                r.resonancePerSecond += r.completionsPerSecond[i] * cfg.baseResonance * resonanceMultiplier(i)
            }
        }
        return r
    }

    func cycleSeconds(_ i: Int) -> Double {
        let cps = cachedRates.completionsPerSecond[i]
        return cps > 0 ? 1 / cps : .infinity
    }

    func progress(_ i: Int) -> Double {
        min(1, max(0, state.loops[i].charge / requirement(i)))
    }

    /// 0…1, decaying, for the completion flash.
    func glow(_ i: Int) -> Double {
        let age = now - lastCompletion[i]
        guard age >= 0, age < 1 else { return 0 }
        return exp(-age * 7)
    }

    // MARK: - Offline

    private var offlineEfficiency: Double {
        if state.nodes.contains("offline2") { return 1.0 }
        if state.nodes.contains("offline1") { return 0.85 }
        return 0.6
    }

    private var offlineCap: Double {
        if state.nodes.contains("offline2") { return 24 * 3600 }
        if state.nodes.contains("offline1") { return 12 * 3600 }
        return 4 * 3600
    }

    func applyOfflineProgress() {
        let elapsed = Date().timeIntervalSince(state.lastSeen)
        guard elapsed > 60 else {
            state.lastSeen = Date()
            return
        }
        let effective = min(elapsed, offlineCap) * offlineEfficiency
        let before = (state.energy, state.resonance, state.loops.reduce(0.0) { $0 + $1.completions })

        recordCompletions = false
        let step = min(0.5, max(0.02, effective / 4000))
        var remaining = effective
        var guardCount = 0
        while remaining > 0 && guardCount < 5000 {
            let d = min(step, remaining)
            tick(d)
            remaining -= d
            guardCount += 1
        }
        recordCompletions = true

        let after = (state.energy, state.resonance, state.loops.reduce(0.0) { $0 + $1.completions })
        state.lastSeen = Date()
        offlineReport = OfflineReport(elapsed: elapsed,
                                      efficiency: offlineEfficiency,
                                      energy: after.0 - before.0,
                                      resonance: after.1 - before.1,
                                      completions: after.2 - before.2)
    }

    // MARK: - Persistence

    private var saveURL: URL {
        let dir = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        return dir.appendingPathComponent("cascade-save.json")
    }

    func save() {
        do {
            let data = try JSONEncoder().encode(state)
            try data.write(to: saveURL, options: .atomic)
        } catch {
            print("Cascade: save failed — \(error)")
        }
    }

    func load() {
        guard let data = try? Data(contentsOf: saveURL),
              let loaded = try? JSONDecoder().decode(GameState.self, from: data) else { return }
        state = loaded
        // Tolerate a save written before a loop was added to the config.
        while state.loops.count < LoopConfig.count { state.loops.append(LoopState()) }
        if state.loops.count > LoopConfig.count { state.loops.removeLast(state.loops.count - LoopConfig.count) }
        state.loops[0].unlocked = true
    }

    func hardReset() {
        state = GameState.new()
        lastCompletion = [Double](repeating: -999, count: LoopConfig.count)
        save()
    }

    // MARK: - Feel

    #if canImport(UIKit)
    private func haptic(_ style: UIImpactFeedbackGenerator.FeedbackStyle) {
        UIImpactFeedbackGenerator(style: style).impactOccurred()
    }
    #else
    private enum HapticStyle { case light, medium, heavy }
    private func haptic(_ style: HapticStyle) {}
    #endif
}
